version: 2
updates:

  - package-ecosystem: "nuget"
    directory: "/Parallel.Cli"
    schedule:
      interval: "daily"
    target-branch: "main"

  - package-ecosystem: "nuget"
    directory: "/Parallel.Core"
    schedule:
      interval: "daily"
    target-branch: "main"

  - package-ecosystem: "nuget"
    directory: "/Parallel.Desktop"
    schedule:
      interval: "daily"
    target-branch: "main"
